import type { Metadata } from "next";
import { Geist, Kanit } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const kanit = Kanit({
  subsets: ["thai"],
  weight: ['100','200', '300', '400', '500', '600'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${kanit.className} `}
      >
        {children}
      </body>
    </html>
  );
}
